cursor #e2e2e2
cursor_text_color #c6c6c6

foreground            #e2e2e2
background            #131313
selection_foreground  #1c3437
selection_background  #b1cbcf
url_color             #4dd8e7

color0   #131313
color1   #ff4385
color2   #4ce75b
color3   #fff143
color4   #2bcadb
color5   #00606a
color6   #4dd8e7
color7   #dff0f2
color8   #879496
color9   #ff7fab
color10  #88ff92
color11  #fff688
color12  #6ef0fe
color13  #88f3ff
color14  #b2f7ff
color15  #f6feff
